FROM ruby:slim

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends apt-utils && \
    apt-get install -qq curl && \
    apt-get install -qq unzip && \
    apt-get install -qq git && \
    apt-get install -qq gcc

